[project]
name = "myproject"
version = "0.1.0"
dependencies = [
    "pyyaml==6.0.*",
    "textual==0.89.*",
    "psutil==6.1.*"
]

[tool.setuptools.packages.find]
where = ["src","resources"] 
include = ["code*"]
exclude = [] 